### ISSUE TITLE
Mappable does not support null field values

### ISSUE THREAD

**Issue by ggreaves** [aol/cyclops#76]
AsMappable.asMappable(new MyEntity(10,"hello")).toMap();

If MyEntity has any null field values the following error occurs:

java.lang.NullPointerException
	at java.util.HashMap.merge(HashMap.java:1216)
	at java.util.stream.Collectors.lambda$53(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.aol.cyclops.lambda.api.Mappable.toMap(Mappable.java:31)
	at TestCyclopsMappable2.test(TestCyclopsMappable2.java:29)

This appears to be due to the way Collectors.toMap() handles (or doesn't handle) null values
see: http://stackoverflow.com/q/24630963/4931921

Regards,
Grant

**Comment by johnmcclean-aol** [comment]
Thanks Grant - I've submitted a Pull Request for this issue.

**Comment by johnmcclean-aol** [comment]
released in 6.2.1
